workout1
================
Madison Tagg

The Best is the Golden State Warriors. But Who is the Best Warrior on the Golden State NBA Team?
================================================================================================

<img src="/Users/madisontagg/Desktop/workout01/images/Stephsface.jpg" width="60%" style="display: block; margin: auto;" />

The Golden State Warriors, based out of the city of Oakland, has dominated the league ever since Steph Curry, Klay Thompson, Draymond Green and Kevin Durant have been together. The "Splash-Brothers", Steph Curry and Klay Thompson, with the addition of Kevin Durant are arguable the best players in the league. In addition to their dominated in outside shooting, Draymond Green's aggressive intimidation and Andre Iguodala's experience is not to play around either.

#### Motivation:

Just because one scores more points, Is that person the best player on the team? I always hated when someone on my team kept shooting even though they were a terrible shooter. The reason that I have constructed this report is to see who is a **consistent** shooter on the Golden State Warriors team. Consistency brings a lot to a team and can push a team to be the very best. This can be consistency on defense or offensive, but in this report we will be focusing on consistency in shooting percentages.

#### Background:

<img src="/Users/madisontagg/Desktop/workout01/images/headshotSC.jpg" width="20%" style="display: block; margin: auto;" /> Stephan Curry, also knows as the Baby-Faced Assassin or Chef curry, was born in March 14, 1988. He stands tall at 6'3" (which is quite short in the league) and weights 190 lbs. He has two daughters, Riley and Ryan, and a son named Canon W. Jack Curry. He met his wife, Ayesha Curry, in College at Dividson College and got married in 2011. <img src="/Users/madisontagg/Desktop/workout01/images/headshotKD.jpg" width="20%" style="display: block; margin: auto;" /> You can call him a Durantula or Slim Reaper becuase that's just what he is. He dominates on the court in many aspects, playing Small forward or Power Forward or Shooting Guard. He was born on September 29th, 1988 in Washington, DC. He stands well above many competors at 6'9" and weighs a solid 240 lbs. He has shown dominance even from his collegiate years at the University of Texas, as he was drafted the second overall pick by the Seattle SuperSonices in 2007. <img src="/Users/madisontagg/Desktop/workout01/images/headshotDG.jpg" width="20%" style="display: block; margin: auto;" /> Many competitors despise this man, Draymond Green, "Money23Green". He is always looking for fights and looking to get inside competitors heads. He is a small Forward and a Power Forward standing at 6'7" weighing 230 lbs. He was born on March 4th, 1990 in Saginaw, Michigan. <img src="/Users/madisontagg/Desktop/workout01/images/headshotAI.jpg" width="20%" style="display: block; margin: auto;" /> Pronounced ig-uh-DAH-luh, he comes from the University of Arizona and was born January 28, 1984. He has played 12 years in the league and specifically plays as a Shooting Guard or Small Forward. He is 6'6" and weighs 215lbs. He is married to Christina Gutierrez and they got married in 2015. <img src="/Users/madisontagg/Desktop/workout01/images/headshotKT.jpg" width="20%" style="display: block; margin: auto;" /> As one of the legendary splash brothers, Klay Thompson does not disappoint. He plays as a Shooting guard specifically deep in the wings. He was born in Los Angeles California, on February 8th, 1990. He attended Washington State University where he also succeed in his 3-point percentages.

#### Data:

<img src="/Users/madisontagg/Desktop/workout01/images/gsw-shot-charts.pdf" width="80%" style="display: block; margin: auto;" />

    ## 
    ## Attaching package: 'dplyr'

    ## The following objects are masked from 'package:stats':
    ## 
    ##     filter, lag

    ## The following objects are masked from 'package:base':
    ## 
    ##     intersect, setdiff, setequal, union

    ##             name made total_shots three_pointers_perc_made
    ## 1  Klay Thompson  246         580                0.4241379
    ## 2  Stephen Curry  280         687                0.4075691
    ## 3   Kevin Durant  105         272                0.3860294
    ## 4 Andre Iguodala   58         161                0.3602484
    ## 5 Graymond Green   74         232                0.3189655

    ##             name made total_shots two_pointers_perc_made
    ## 1 Andre Iguodala  134         210              0.6380952
    ## 2   Kevin Durant  390         643              0.6065319
    ## 3  Stephen Curry  304         563              0.5399645
    ## 4  Klay Thompson  329         640              0.5140625
    ## 5 Graymond Green  171         346              0.4942197

    ##             name made total_shots total_perc_made
    ## 1   Kevin Durant  495         915       0.5409836
    ## 2 Andre Iguodala  192         371       0.5175202
    ## 3  Klay Thompson  575        1220       0.4713115
    ## 4  Stephen Curry  584        1250       0.4672000
    ## 5 Graymond Green  245         578       0.4238754

#### Analysis:

Looking at the Graphics of where each players shots were taken and where specifically, the green ones were located, we get a beautiful representation of the player's accuracy. For instance, we can see that Andre Iguodala took less shots on around the three point line and we can wee that Steph Curry and Klay Thompson took a lot around the three point line. As far as the color of these graphic representations, we can see a lot of red dots around the three point line for both Draymond Green and Steph Curry. Let's take a deeper look into the statistics computed in the tables above.

As we can see in the data section above, we can see that in the Data above that the winners for the most Three pointers was **Klay Thompson**. I guess you could say that he is the better splash brother, Steph Curry, when it comes to threes. Klay Thompson successfully made **246** out of **580** which ultimetly, made his three pointer percentage at about **42%**. Due to his ability to finish when attempting to shoot a three, Klay Thompson has a higher percentage than Steph Curry, who came in at a close second behind Klay. Steph Curry finsihed with **280** made threes out of **687** attemps. Even though one could argue that Steph made more threes than Klay and should be the reigning champion of three pointers, the percentage doesn't lie, around **41%**.

If we can take a look at the two pointers made from each of the players, the winner is...**Andre Iguodala**. His percentage for finishing his two point shots was at an outstanding **64%**. His attemps were only **210** which was significantly lower than second place **Kevin Durant** at **643**. The difference is that **Kevin Durant** only finished \*\*61%\* of shots, which was 390.

ANDDDDD the overall winning for both two pointers and three pointers was **KEVIN DURANT**. His percentage to finish shots was at **54%**. The 915 shots taken, Durant finished 495 which is pretty outstanding. Closely behind him was Andre Iguodala, who was 192 out of 371, which gave him the average of **52%**. In last place for both two and three points scored, was Draymond Green. His fiesty attitude was no match when it came to finishing shots. He percentage for finishing was **43%**. Even though that would be a lot better than anything that i could have done, In the league, that is not good.

#### Discussion:

Even though percentage provides a great representation for a player that is constistent when finishing shots taken, do you think that making more points makes the player better even though the attemps are higher? The legendary Steph Curry, known for making a large amount of three-pointers failed in making the top spot in three-point percentage. He made the most three pointers on the team at 280 but his attempts were through the roof. We can also look at two-pointers made and the percentages as well. Kevin Durant is arguably the best player with 390 made two points shots but his percentage is below Andre Iguodala's due to his 643 attempts. So is the best player on the court the one that has a higher percentage of points scored or should we look at the player that has scored the most shots?

#### Conclusions:

In conclusion, looking at Steph Curry, Kevin Durant, Draymond Green, Andre Iguodala and Klay Thompson, the best play on the Golden State Warriors is Kevin Durant. We can look at specifically three-point percentage or two-point percentage but looking at overall percentage to finishing shots, Kevin Durant is arguably better based on the data constructed. What people in the world of basketball wouldn't guess is that Steph Curry is in third place with a percentage of 47%. Steph made more points that Kevin Durant's 495 with an outstanding 584. I guess the quote "You'll never score if you don't take the shot" came in handy to Steph with his large number of attempts.

#### References:

<https://www.google.com/search?q=steph+curry&rlz=1C5CHFA_enUS704US722&source=lnms&tbm=isch&sa=X&sqi=2&ved=0ahUKEwix7PS004DhAhVTwcQBHTOqB6IQ_AUIDygC&biw=874&bih=653#imgrc=burXfpJU-M_SDM:> <https://www.basketball-reference.com/teams/GSW/2017.html> <https://www.basketball-reference.com/players/c/curryst01.html> <https://www.basketball-reference.com/players/i/iguodan01.html> <https://www.basketball-reference.com/players/d/duranke01.html> <https://www.basketball-reference.com/players/g/greendr01.html> <https://www.basketball-reference.com/players/t/thompkl01.html>
